### PR TITLE
Fix: Changed to work correctly with Blender 4.0 or later

### PR DESCRIPTION
**Pull request by Puls-r**
- Removed bgl
- Changed shader from 3D_UNIFORM_COLOR to UNIFORM_COLOR
- changed use bgl to gpu

### CODE REVIEW

**Comment by schroef** [comment]
That's awesome! I did try it at the beginning of 4
0 release, but didn't had the time to find out how to get this working again. Goad you did

**Comment by Puls-r** [comment]
I hope this was helpful. ✨🙂

**Comment by schroef** [comment]
Ill add it to my version, ive done some different work a while back making some items easier.

**Comment by schroef** [comment]
Your edits work like a champ! I did some more edits to my version. My updates allows a user to change the onion object when they are in pose mode. There was an issue with this, because a user needs to go out if oose node selext the mesh object and only then could they update the onion preview. I've changed this behavior now. This also allows for the user to select different parts of the children of a armature. Lots of times a character is made out of separate parts. The best workflow would perhaps be to merge everything and then do a onion preview. But that is a huge change to the current workflow. Also kinda difficult to tackle because people setup everything totally different from one another.

I'll try to post my branch asap

**Comment by iBrushC** [comment]
Hey all! So sorry for the inactivity. I've been abroad for a while and didn't have access to my GitHub account. Thanks so much for keeping this going, I'll try to get this update posted to BlenderMarket and Gumroad as soon as possible.

**Pull request merged**
